### ISSUE TITLE
Bug: 未兼容新版本数据库

### ISSUE THREAD

**Issue by Lipraty** [koishijs/koishi-plugin-dialogue#20]
![)4MBM8 KU%O_8L5WE@~TPLJ](https://user-images.githubusercontent.com/18106422/230431461-e7aa4c13-0050-4e81-b83c-cce08728fee9.jpg)

抄送自里裙安妮（

**Comment by shigma** [comment]
author 插件限定问题，停用 author 插件可暂时解决。

**Comment by shigma** [comment]
已修复。
