### ISSUE TITLE
以 @bot 开头的消息无法正确触发仅前缀匹配的问答

### ISSUE THREAD

**Issue by dragon-fish** [koishijs/koishi-plugin-dialogue#23]
从某个版本开始， `probA=1 probS=0`的问答无法通过 @bot 触发，与较早版本中的行为不一致

**如何复现**

![image](https://github.com/koishijs/koishi-plugin-dialogue/assets/44761872/af1876a5-7218-4656-994e-ac5e5e91fc4a)

**期待行为**

最后一个消息能触发回答

**Comment by asasdsaweasd** [comment]
想问一下这个问题定位到了吗，我也遇到这个问题了

**Comment by shigma** [comment]
暂时产能不足，估计两周左右修。

**Comment by asasdsaweasd** [comment]
> 暂时产能不足，估计两周左右修。

好的，辛苦了

**Comment by shigma** [comment]
已修复，将于下个版本实装。

**Comment by asasdsaweasd** [comment]
想问一下 `await u3g1.shouldReply(`<at id="${app.mock.bots[0].selfId}"/> foo`, 'bar')`可以匹配到<at id="机器人qq" name="机器人的群昵称" />吗 从red获取到at的是带name的

**Comment by shigma** [comment]
可以

**Comment by asasdsaweasd** [comment]
好的 感谢
