### ISSUE TITLE
设置有图片的问答时机器人反馈“上传资源时发生错误。”

### ISSUE THREAD

**Issue by litterkidfeng** [koishijs/koishi-plugin-dialogue#24]
设置有图片的问答时机器人反馈“上传资源时发生错误。”
![V4_)79R0S_~9OOLC`7X NNI](https://github.com/koishijs/koishi-plugin-dialogue/assets/141178871/200d86ca-ba7a-4fbf-8541-c14dc50f4b98)

**Comment by shigma** [comment]
请提供完整的错误信息。

**Comment by litterkidfeng** [comment]
好的，添加问答的时候，纯文字类的可以被添加，而上传带有图片的问答则提示“上传资源时发生错误”
![{7%LSF` X7J`JD _57PIFI_tmb](https://github.com/koishijs/koishi-plugin-dialogue/assets/141178871/fff0f74f-20a3-4549-8de5-560c4502a2ca)

而在日志文件中，添加图片问答出错会报这样的一条错误。
![GAD1Z7 H2PS}$Z%YD1BPZK6](https://github.com/koishijs/koishi-plugin-dialogue/assets/141178871/757a2e9d-c917-45e0-84e4-cb8b3f00a43f)

我的koishi版本如下图：
![WD}J{`SNE12A87 )M}2$IW4](https://github.com/koishijs/koishi-plugin-dialogue/assets/141178871/13f55ec5-25d6-412d-b5ae-d9a0d8696b7a)

这是我koishi界面的dialogue：
![)YM`$JZ552{3D{349$NURUV](https://github.com/koishijs/koishi-plugin-dialogue/assets/141178871/c3787e94-025f-4c6b-bfa5-7f6175e6e50b)

**Comment by litterkidfeng** [comment]
问过其他dialogue用户，他们并没有出现这样的问题，我同时也会排查一下电脑自身的问题

**Comment by shigma** [comment]
你的 assets 插件使用的预装 assets-local 吗？

**Comment by litterkidfeng** [comment]
是的

**Comment by litterkidfeng** [comment]
你好，我使用的是chronocat，奇怪的是，我将koishi更新到4.14.4之后，问题得到了解决，并且在我退回koishi版本再进行测试，图片问答也能正常添加了。现在没有报错，如果我在接下来的使用中再次遇到该问题或者是其他问题，我会第一时间向你反馈错误日志，感谢你的辛勤付出！

**Comment by shigma** [comment]
解决了就太好了。以后如果有发生可以 reopen 这个 issue。
