### ISSUE TITLE
希望增加当无权限的人使用时，不返回提示的按钮

### ISSUE THREAD

**Issue by asasdsaweasd** [koishijs/koishi-plugin-dialogue#26]
![image](https://github.com/koishijs/koishi-plugin-dialogue/assets/47250180/726cd7e4-b957-438e-8ceb-94ddb94945d9)
防止刷屏

**Comment by axlmly** [comment]
本地化内可以清除

**Comment by asasdsaweasd** [comment]
> 本地化内可以清除

有步骤吗

**Comment by axlmly** [comment]
![chrome_BsA7xXZBKe](https://github.com/koishijs/koishi-plugin-dialogue/assets/41771421/6b835407-eef6-4be4-987b-b349aca3e778)
将文本清空
