### ISSUE TITLE
dialogue 插件报错

### ISSUE THREAD

**Issue by sheep2007** [koishijs/koishi-plugin-dialogue#27]
dialogue 插件疯狂警告刷日志

![image](https://github.com/koishijs/koishi-plugin-dialogue/assets/122354009/c8c79f10-b6bf-4eb6-90cf-9dc3f93bedc6)

每接收到一条消息就有两条警告消息

**Comment by shigma** [comment]
收到，会尽快修复。

**Comment by shigma** [comment]
好像已经修完忘记发版了，刚刚发了一版，请用最新版本试试。
