### ISSUE TITLE
Q群官方机器人无法发送图片

### ISSUE THREAD

**Issue by KuroshioDev** [koishijs/koishi-plugin-dialogue#29]
![image](https://github.com/koishijs/koishi-plugin-dialogue/assets/40047545/c4dde6b4-fd34-4d64-8605-cdb5582e8fbf)

已安装server-temp

**Comment by shigma** [comment]
可能是因为你的 selfUrl 无法访问。

**Comment by KuroshioDev** [comment]
> 可能是因为你的 selfUrl 无法访问。

我没有设置url，但是频道里面可以发送图片，请问这是为什么

**Comment by KuroshioDev** [comment]
> > 我没有设置url，但是频道里面可以发送图片，请问这是为什么
> 
> 因为频道支持上传图片，群不支持，所以必须使用公网 URL。

![image](https://github.com/koishijs/koishi-plugin-dialogue/assets/40047545/17264cc9-bdea-4599-a0f5-c3388c19e871)

文本也没反应

**Comment by shigma** [comment]
默认情况下创建的问答不会响应不带 @ 的消息。考虑到 QQ 平台的限制，未来将修改这个默认行为。

在修改前，可以使用 `# foo bar -P 1` 来创建可以被 @ 触发的问答。

**Comment by shigma** [comment]
由于从标题看此 issue 已经解决，故 close。

前面提到的未解决的部分我会另开一个 issue。
