### ISSUE TITLE
报错：no such function:REGEXP

### ISSUE THREAD

**Issue by wuwo020** [koishijs/koishi-plugin-dialogue#6]
报错信息应该是：no such function:REGEXP

**Comment by shigma** [comment]
看起来你使用的是 sqlite 插件，请提供下列插件的版本：

- @koishijs/plugin-database-sqlite
- koishi-plugin-dialogue

**Comment by wuwo020** [comment]
所有插件均为最新版本


koishijs/plugin-database-sqlite：3.0.3
koishi-plugin-dialogue：4.0.5

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月15日(周四) 凌晨1:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [koishijs/koishi-plugin-dialogue] 报错：no such function:REGEXP (Issue #6)




 
看起来你使用的是 sqlite 插件，请提供下列插件的版本：
  
@koishijs/plugin-database-sqlite
 
koishi-plugin-dialogue

**Comment by shigma** [comment]
有点奇怪，我根本没有使用一个叫 regexp 的函数。你能提供更多的错误日志吗？

**Comment by wuwo020** [comment]
重装太多次了，文件没了，但是通过我今天的十次重装回退经验，我大致发现了问题所在：
1.koishi进行了4.10.6的一次版本更新，更新后会出现稳定的报错
2.报错提示我的path没装ffmpeg，会出现QQ无法接收到返回的图片或者视频，安装后恢复
3.其余情况下正常
&nbsp;


1602169603
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月15日(星期四) 下午2:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [koishijs/koishi-plugin-dialogue] 报错：no such function:REGEXP (Issue #6)





 
有点奇怪，我根本没有使用一个叫 regexp 的函数。你能提供更多的错误日志吗？

**Comment by shigma** [comment]
那先等其他人复现吧。我暂时无法定位问题。

Koishi 4.10.6 未进行任何 dialogue 或者 sqlite 的改动，因此与你的问题毫无关系。

此外，ffmpeg 也跟 Koishi 毫无关系，这是你使用 gocq 所必要的步骤。后续会考虑在安装过程中预装 ffmpeg。

**Comment by Seidko** [comment]
fix in [shigma/minato@b97163](https://github.com/shigma/minato/commit/b97163c6d2a958f54f0129688152b471102f6f62)
